"""
Visual LLM Post-Fill Form Auditor Module

Audits web form state post-filling by checking HTML5 input validity, CSS error classes,
and required fields, and taking full-page screenshots to visually verify submission readiness.
"""

import asyncio
import logging
from dataclasses import dataclass, field
from pathlib import Path
from typing import List, Dict, Any, Optional
from playwright.async_api import Page

logger = logging.getLogger(__name__)


@dataclass
class AuditError:
    """Represents a form validation error found post-fill."""
    field_identifier: str
    error_message: str
    error_type: str  # 'invalid_input', 'missing_required', 'error_class', 'visible_error_text'


@dataclass
class VisualAuditReport:
    """Report generated by VisualFormAuditor."""
    is_valid: bool
    total_errors: int
    errors: List[AuditError] = field(default_factory=list)
    screenshot_path: Optional[str] = None
    summary: str = ""

    def to_dict(self) -> Dict[str, Any]:
        return {
            "is_valid": self.is_valid,
            "total_errors": self.total_errors,
            "errors": [
                {
                    "field": e.field_identifier,
                    "message": e.error_message,
                    "type": e.error_type
                }
                for e in self.errors
            ],
            "screenshot_path": self.screenshot_path,
            "summary": self.summary
        }


class VisualFormAuditor:
    """
    Post-fill visual & DOM auditor for job application forms.
    Inspects invalid state, red error labels, and missing required fields before submission.
    """

    def __init__(self, page: Page):
        self.page = page

    async def audit_form(self, screenshot_dir: Optional[str] = None) -> VisualAuditReport:
        """
        Audit the current page form for any active frontend errors or missing required fields.
        
        Args:
            screenshot_dir: Optional directory path to save full-page verification screenshot.
            
        Returns:
            VisualAuditReport object with audit results.
        """
        errors: List[AuditError] = []

        try:
            frames = self.page.frames if hasattr(self.page, "frames") and self.page.frames else [self.page]

            for target in frames:
                try:
                    # 1. Check for HTML5 invalid inputs: input:invalid, select:invalid, textarea:invalid
                    invalid_elements = await target.query_selector_all("input:invalid, select:invalid, textarea:invalid")
                    for el in invalid_elements:
                        if await el.is_visible():
                            name_or_id = await el.evaluate("el => el.getAttribute('name') || el.getAttribute('id') || el.tagName")
                            validation_msg = await el.evaluate("el => el.validationMessage || 'Invalid field value'")
                            errors.append(AuditError(
                                field_identifier=name_or_id,
                                error_message=validation_msg,
                                error_type="invalid_input"
                            ))

                    # 2. Check for active CSS error classes: .error, .has-error, .is-invalid, .field-error, etc.
                    error_selectors = [
                        ".error", ".has-error", ".is-invalid", ".field-error", 
                        ".invalid-feedback", "[class*='error']", "[class*='invalid']"
                    ]
                    error_keywords = [
                        'required', 'must be', 'should be', 'please enter', 'invalid', 
                        'value should', 'field is required', 'resume is required', 'valid number'
                    ]
                    for selector in error_selectors:
                        try:
                            err_nodes = await target.query_selector_all(selector)
                            for node in err_nodes:
                                if await node.is_visible():
                                    txt = (await node.text_content() or "").strip()
                                    if txt and len(txt) < 200 and any(kw in txt.lower() for kw in error_keywords):
                                        node_id = await node.evaluate("el => el.getAttribute('id') || el.getAttribute('class')")
                                        if not any(e.error_message == txt for e in errors):
                                            errors.append(AuditError(
                                                field_identifier=node_id or selector,
                                                error_message=txt,
                                                error_type="error_class"
                                            ))
                        except Exception:
                            pass

                    # 3. Check for empty required fields
                    required_inputs = await target.query_selector_all("input[required], select[required], textarea[required]")
                    for req in required_inputs:
                        if await req.is_visible():
                            val = await req.input_value() if await req.evaluate("el => 'value' in el") else ""
                            if not val or not val.strip():
                                name_or_id = await req.evaluate("el => el.getAttribute('name') || el.getAttribute('id') || el.getAttribute('placeholder')")
                                if not any(e.field_identifier == name_or_id for e in errors):
                                    errors.append(AuditError(
                                        field_identifier=name_or_id or "Required field",
                                        error_message="Required field is empty",
                                        error_type="missing_required"
                                    ))
                except Exception as frame_err:
                    logger.debug(f"Error auditing frame {target}: {frame_err}")

            # 4. Take full-page visual verification screenshot
            screenshot_path = None
            if screenshot_dir:
                try:
                    p = Path(screenshot_dir)
                    p.mkdir(parents=True, exist_ok=True)
                    screenshot_path = str(p / "post_fill_audit.png")
                    await self.page.screenshot(path=screenshot_path, full_page=True)
                    logger.info(f"📸 Visual post-fill audit screenshot saved to: {screenshot_path}")
                except Exception as e:
                    logger.warning(f"Could not take audit screenshot: {e}")

        except Exception as e:
            logger.error(f"Error during visual form audit: {e}")

        is_valid = len(errors) == 0
        summary = "Form post-fill visual audit PASSED with 0 errors." if is_valid else f"Form post-fill visual audit FAILED with {len(errors)} active errors."

        report = VisualAuditReport(
            is_valid=is_valid,
            total_errors=len(errors),
            errors=errors,
            screenshot_path=screenshot_path,
            summary=summary
        )
        logger.info(f"📋 Audit Summary: {summary}")
        return report
